import {
  chickpea,
  dates,
  coffeebeans,
  flour,
  pasta,
  rice,
  salt,
  sugar,
  apple,
  blackberries,
  blueberries,
  corn,
  cucumber,
  potato,
  redberries,
  strawberries,
  tomato,
  almond,
  dryedapricots,
  hazelnut,
  peanut,
  pistachios,
  walnut,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1005,
    title: "Stations",
    link: "/journal",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  }
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: chickpea,
    productName: "Chickpea",
    price: "6.00",
    color: "Blank and White",
    badge: false,
    des: "500 gr Checkpea %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "202",
    img: coffeebeans,
    productName: "Coffee Beans",
    price: "11.00",
    color: "Gray",
    badge: false,
    des: "500 gr Coffee Beans %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "203",
    img: flour,
    productName: "Flour",
    price: "25.00",
    color: "Mixed",
    badge: false,
    des: "Flour (Mehl) 1050 (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "204",
    img: pasta,
    productName: "Pasta",
    price: "2.00",
    color: "Black",
    badge: false,
    des: "500 gr Pasta (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "205",
    img: rice,
    productName: "Rice",
    price: "4.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Rice with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "206",
    img: salt,
    productName: "Salt",
    price: "5.00",
    color: "Black",
    badge: false,
    des: "500 gr Salt from Alps with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "207",
    img: sugar,
    productName: "Sugar",
    price: "25.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Sugar (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "209",
    img: apple,
    productName: "Apple",
    price: "5.00",
    color: "Mixed",
    badge: false,
    des: "1 kg Apple %100 Local (Qualitat aus Deutschland) with Sustainable Paper Packages.",
    cat: "produce",
  },
  {
    _id: "210",
    img: blackberries,
    productName: "Blackberries",
    price: "7.00",
    color: "Black",
    badge: false,
    des: "500 gr Blackberries %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "produce",
  },
  {
    _id: "211",
    img: corn,
    productName: "Corn",
    price: "2.00",
    color: "Mixed",
    badge: false,
    des: "Single Piece %100 Local (Qualitat aus Deutschland) with Sustainable Paper Packages.",
    cat: "produce",
  },
  {
    _id: "212",
    img: cucumber,
    productName: "Cucumber",
    price: "5.00",
    color: "Black",
    badge: false,
    des: "1 kg Cucumber %100 Local (Qualitat aus Deutschland) with Sustainable Paper Packages.",
    cat: "produce",
  },
  {
    _id: "213",
    img: potato,
    productName: "Potato",
    price: "5.00",
    color: "Mixed",
    badge: false,
    des: "1 kg Bio Potato %100 Local (Qualitat aus Deutschland) with Sustainable Paper Packages.",
    cat: "produce",
  },
  {
    _id: "214",
    img: redberries,
    productName: "Redberries",
    price: "7.00",
    color: "Black",
    badge: false,
    des: "500 gr Redberries %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "produce",
  },
  {
    _id: "215",
    img: strawberries,
    productName: "Strawberries",
    price: "7.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Strawberries %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "produce",
  },
  {
    _id: "216",
    img: tomato,
    productName: "Tomato",
    price: "5.00",
    color: "Black",
    badge: false,
    des: "1 kg Bio Tomato %100 Local (Qualitat aus Deutschland) with Sustainable Paper Package.",
    cat: "produce",
  },
  {
    _id: "217",
    img: almond,
    productName: "Almonod",
    price: "14.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Almond (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "219",
    img: dates,
    productName: "Dates",
    price: "11.00",
    color: "Black",
    badge: false,
    des: "500 gr Dates with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "220",
    img: dryedapricots,
    productName: "Dryed Apricots",
    price: "18.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Dryed Apricots with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "221",
    img: hazelnut,
    productName: "Hazelnut",
    price: "16.00",
    color: "Black",
    badge: false,
    des: "500 gr Hazelnut (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "222",
    img: peanut,
    productName: "Peanut",
    price: "8.00",
    color: "Black",
    badge: false,
    des: "500 gr Bio Peanut (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "223",
    img: pistachios,
    productName: "Pistachios",
    price: "21.00",
    color: "Black",
    badge: false,
    des: "500 gr Pistachios with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "224",
    img: walnut,
    productName: "Walnut",
    price: "18.00",
    color: "Black",
    badge: false,
    des: "500 gr Walnut (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "225",
    img: blueberries,
    productName: "Blueberries",
    price: "8.00",
    color: "Black",
    badge: false,
    des: "500 gr Blueberries %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "produce",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  /*
  {
    _id: "201",
    img: IMPRIMANTE_PANTUM_CP2200DW,
    productName: "Imprimante PANTUM CP2200DW",
    price: "35.00",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Imprimante Laser PANTUM Couleur - Fonctions: Impression  - Technologie d'impression: Laser - Format Papier: A4 - Vitesse d’impression(Couleur/N&B): 24 ppm (A4) / 26 ppm (Lettre) - Résolution d'impression: 600 x 600 dpi - Sortie papier: 100 page - Mémoire: Double cœur, 1 GHz - Impression recto verso: Automatique - Heure de la première impression: Moins de 11s  - Connecteurs: USB 2.0 haut débit Ethernet 10/100/1000 BaseTX (RJ-45) 802.11b/g/n Sans fil - Dimensions: 411.2 x 394.1 x 243.7mm - Poids: 16,1 kg - Couleur: Blanc",
    cat: "essentials",
    pdf: pdf1,
    ficheTech: [
      { label: "Technology ", value: "Electrophotographic monochrome laser " },
      { label: "Print speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

      { label: "First print out time ", value: "Less than 7.8s       " },
      { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
      {
        label: "Recommended monthly volume Resolution(dpi) ",
        value: "700 pages ",
      },
      { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
      { label: "Printer  ", value: "Max. 1,2   " },
      { label: "galass  ", value: "Max. 1,2   " },
    ],
  },
  */
  {
    _id: "201",
    img: chickpea,
    productName: "Chickpea",
    price: "6.00",
    color: "Blank and White",
    badge: false,
    des: "500 gr Checkpea %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "202",
    img: coffeebeans,
    productName: "Coffee Beans",
    price: "11.00",
    color: "Gray",
    badge: false,
    des: "500 gr Coffee Beans %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "203",
    img: flour,
    productName: "Flour",
    price: "25.00",
    color: "Mixed",
    badge: false,
    des: "Flour (Mehl) 1050 (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "204",
    img: pasta,
    productName: "Pasta",
    price: "2.00",
    color: "Black",
    badge: false,
    des: "500 gr Pasta (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "205",
    img: rice,
    productName: "Rice",
    price: "4.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Rice with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "206",
    img: salt,
    productName: "Salt",
    price: "5.00",
    color: "Black",
    badge: false,
    des: "500 gr Salt from Alps with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "207",
    img: sugar,
    productName: "Sugar",
    price: "25.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Sugar (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "pantry",
  },
  {
    _id: "209",
    img: apple,
    productName: "Apple",
    price: "5.00",
    color: "Mixed",
    badge: false,
    des: "1 kg Apple %100 Local (Qualitat aus Deutschland) with Sustainable Paper Packages.",
    cat: "produce",
  },
  {
    _id: "210",
    img: blackberries,
    productName: "Blackberries",
    price: "7.00",
    color: "Black",
    badge: false,
    des: "500 gr Blackberries %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "produce",
  },
  {
    _id: "211",
    img: corn,
    productName: "Corn",
    price: "2.00",
    color: "Mixed",
    badge: false,
    des: "Single Piece %100 Local (Qualitat aus Deutschland) with Sustainable Paper Packages.",
    cat: "produce",
  },
  {
    _id: "212",
    img: cucumber,
    productName: "Cucumber",
    price: "5.00",
    color: "Black",
    badge: false,
    des: "1 kg Cucumber %100 Local (Qualitat aus Deutschland) with Sustainable Paper Packages.",
    cat: "produce",
  },
  {
    _id: "213",
    img: potato,
    productName: "Potato",
    price: "5.00",
    color: "Mixed",
    badge: false,
    des: "1 kg Bio Potato %100 Local (Qualitat aus Deutschland) with Sustainable Paper Packages.",
    cat: "produce",
  },
  {
    _id: "214",
    img: redberries,
    productName: "Redberries",
    price: "7.00",
    color: "Black",
    badge: false,
    des: "500 gr Redberries %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "produce",
  },
  {
    _id: "215",
    img: strawberries,
    productName: "Strawberries",
    price: "7.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Strawberries %100 Local (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "produce",
  },
  {
    _id: "216",
    img: tomato,
    productName: "Tomato",
    price: "5.00",
    color: "Black",
    badge: false,
    des: "1 kg Bio Tomato %100 Local (Qualitat aus Deutschland) with Sustainable Paper Package.",
    cat: "produce",
  },
  {
    _id: "217",
    img: almond,
    productName: "Almonod",
    price: "14.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Almond (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "219",
    img: dates,
    productName: "Dates",
    price: "11.00",
    color: "Black",
    badge: false,
    des: "500 gr Dates with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "220",
    img: dryedapricots,
    productName: "Dryed Apricots",
    price: "18.00",
    color: "Mixed",
    badge: false,
    des: "500 gr Dryed Apricots with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "221",
    img: hazelnut,
    productName: "Hazelnut",
    price: "16.00",
    color: "Black",
    badge: false,
    des: "500 gr Hazelnut (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "222",
    img: peanut,
    productName: "Peanut",
    price: "8.00",
    color: "Black",
    badge: false,
    des: "500 gr Bio Peanut (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "223",
    img: pistachios,
    productName: "Pistachios",
    price: "21.00",
    color: "Black",
    badge: false,
    des: "500 gr Pistachios with Sustainable Glass Jars.",
    cat: "snacks",
  },
  {
    _id: "224",
    img: walnut,
    productName: "Walnut",
    price: "18.00",
    color: "Black",
    badge: false,
    des: "500 gr Walnut (Qualitat aus Deutschland) with Sustainable Glass Jars.",
    cat: "snacks",
  },
];
